### ISSUE TITLE
[QUESTION] Exception encountered when running Pathway RAG App in WSL

### ISSUE THREAD

**Issue by robertjak** [pathwaycom/pathway#94]
Hello,

I was following the tutorial [Real-Time AI Pipeline with DeepSeek, Ollama and Pathway](https://pathway.com/blog/deepseek-ollama#real-time-ai-pipeline-with-deepseek-ollama-and-pathway) trying to run the Pathway RAG App without Docker container directly on the WSL (Windows 11) when I after a prompt to the http://0.0.0.0:8000/v1/pw_ai_answer encountered the following error in the app.py script: 

2025-02-14 12:13:35 pathway_engine.engine.dataflow ERROR JSONDecodeError: Expecting ':' delimiter: line 3 column 32 (char 61) in operator 154. Occurred here:
        Line: answer = answer.select(answer=extract_answer(pw.this.answer))
        File: /home/rjak/.local/lib/python3.12/site-packages/pathway/xpacks/llm/question_answering.py:56
        Function: _query_chat_strict_json
2025-02-14 12:13:35 pathway_engine.engine.dataflow ERROR Error value encountered in filter condition, skipping the row in operator 163.
2025-02-14 12:13:35 pathway_engine.engine.dataflow ERROR Error value encountered in filter condition, skipping the row in operator 177.

The Docker container works fine. Please help.

**Comment by berkecanrizai** [comment]
Hi, I assume you are running the [Adaptive RAG](https://pathway.com/developers/templates/template-private-rag#customizing-the-pipeline) that is referenced at the bottom. This exception is thrown from the Adaptive RAG while attempting to parse the model response.

In the case of Adaptive RAG, model responses need to be JSON parsable strings. Can you make sure that your LiteLLM chat instance has the `format` key in the constructor, or in the YAML?

For example:
```yaml
$llm_model: "ollama/mistral"

$llm: !pw.xpacks.llm.llms.LiteLLMChat
  model: $llm_model
  retry_strategy: !pw.udfs.ExponentialBackoffRetryStrategy
    max_retries: 6
  cache_strategy: !pw.udfs.DiskCache
  temperature: 0
  top_p: 1
  format: "json"
  api_base: "http://localhost:11434"
```

Here, `format: "json"` will force model to give JSON outputs. Let us know if the issue persists.
